services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\EventSourcing\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\EventSourcing\Infrastructure\DomainEventStoreInterface: '@Ergonode\EventSourcing\Infrastructure\Store\DbalDomainEventStore'
    Ergonode\EventSourcing\Infrastructure\DomainEventDispatcherInterface: '@Ergonode\EventSourcing\Infrastructure\Dispatcher\SymfonyDomainEventDispatcher'
